language: c

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y ninja-build; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install ninja; fi

script:
  - mkdir build
  - cd build
  - cmake .. -G Ninja
  - ninja
  - ninja test

branches:
  only:
    - master
