language: c

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - ninja-build

install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install -q Sphinx --user `whoami`

script:
  - mkdir build
  - cd build
  - cmake .. -G "Ninja" -DMINDY_BUILD_DOCS=ON
  - ninja
  - ninja test

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1cd1780b9ea4b1fe3eaf
