language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - ninja-build

script:
  - mkdir build
  - cd build
  - cmake .. -G "Ninja"
  - ninja
  - ninja test

branches:
  only:
    - master
